baseurl = "/"
title = "Hugo Themes"
copyright = "Copyright (c) 2008 - 2014, all rights reserved."
languageCode = "en-US"
canonifyurls = true
pagination.pagerSize = 8
theme = "hugo-dusk"
themesDir = "../.."

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Archive"
  weight = -100
  identifier = "archive"
  url = "/archive/"

[taxonomies]
  archive = "archive"
  blog = "blog"
  category = "categories"
  series = "series"
  tag = "tags"
  micro = "micro"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[params.author]
  name = "Author name"
  intro = """\
    'hugo-dusk' theme for [hugo](https://gohugo.io/) an open-source static site generator. \
    For micro posts see [micro](/micro)
  """

